name: recook
description: Recook Market App.
publish_to: "none"

version: 1.2.10-dev+173

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  timeline_tile: 0.1.2
  # 高德定位
  amap_map_fluttify:
  # icons
  flutter_icons: 1.1.0
  # 拼音
  lpinyin: 1.0.9
  # 城市列表
  azlistview: 0.1.2
  # 农历
  lunar_calendar_converter:
    1.0.4+1
    # 进度条
  percent_indicator: ^2.1.7+4
  # 头部滚动视图下拉刷新
  # extended_nested_scroll_view: ^0.3.6
  # 声音播放
  # soundpool: 1.0.1
  ## 暂时关闭声音播放
  #flutter_audio_player: 0.1.2
  # 第三方分享功能
  sharesdk_plugin: 1.2.5

  # 展示二维码
  qr_flutter: ^3.2.0
  # 二维码
  # barcode_scan: ^1.0.0
  flutter_qr_reader:
    git:
      url: https://gitee.com/laiiihz/flutter_qr_reader
      ref: 3e4824752f4fa50c30ecd415341a3a779db01922

  # 网页组件
  webview_flutter: ^0.3.15+1
  # webview_flutter:
  #   git:
  #     url: https://github.com/haysuperman/webview_flutter.git
  #     ref: 7045d9667dfe41c59f5f4a100d2335ec42f4e1de
  #
  url_launcher: ^5.1.3
  # 视频组件
  video_player: ^0.10.11+1
  chewie: ^0.9.10

  # 权限组件
  permission_handler: 3.3.0

  #邀请码相关第三方安装
  openinstall_flutter_plugin: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  sprintf: 4.0.2
  # 分享sdk
  # sharesdk: ^1.1.8
  # 全局状态控制
  flutter_redux: ^0.5.3

  # json解析
  json_annotation: ^2.0.0

  # 路径
  path_provider: ^1.6.11
  path:

  # 网络请求
  dio: ^3.0.9

  # loading界面
  flutter_spinkit: ^3.1.0

  # toast提示
  oktoast: 2.3.2

  # 应用信息
  package_info: 0.4.0+16

  #缓存图片
  #  cached_network_image: ^1.1.0
  extended_text: 4.0.0
  extended_image: 0.9.0
  date_format: 1.0.8
  # image_gallery_saver: ^1.2.1

  # 图片压缩
  flutter_image_compress: 0.6.3
  image_cropper: 1.1.2

  # svg
  flutter_svg: 0.18.1

  # 下拉刷新
  #
  #    现版本将smart_refresher.dart 中的enableOverScroll 去掉了，手动加上，具体代码在refresh_widget.dart中  #########################3
  #
  pull_to_refresh: ^1.6.2
  flutter_gifimage: ^1.0.0

  # 微信登录 支付等
  fluwx: 2.0.7

  #
  # 源码 TobiasPlugin.m
  # 判断支付宝是否安装时  源码不正确  应将 alipays 改为 alipay #########################3
  #
  tobias: 1.6.0+1

  # 小数据缓存
  shared_preferences: 0.5.3+4

  # 屏幕适配
  flutter_screenutil: ^0.5.3

  # banner
  banner_view: ^1.1.2

  # meiqia_plugin: 0.0.2
  meiqia_plugin:
    git:
      url: https://github.com/haysuperman/meiqia
      ref: bfa6b9d81c079a4d1ce86ad611301966fa849538
      # ref: a16c54c40259d4c5bcf8f8da66379fe68a1115f1

  #  flutter_bugly: ^0.2.3+1

  # 加密
  encrypt: 3.2.0

  # 时间选择器
  flutter_datetime_picker: ^1.3.8

  # 侧滑item
  flutter_slidable: 0.5.7
  # flutter_slidable:
  #   git:
  #     url: https://github.com/haysuperman/flutter_slidable
  #     ref: 4073e1ff7db967aad4f97f0eee5909c5f8f339b5

  # 图片选择
  photo: 0.5.0-dev.3
  # wechat_assets_picker: ^2.2.0+2

  image_gallery_saver: 1.5.0
  # 因为项目compileSdkVersion 28
  # 第三方包compileSdkVersion 是27 所以需要修改 不然build会出错
  #
  # flutter_bugly:
  #   git:
  #     url: https://github.com/crazecoder/flutter_bugly.git
  #     ref: dev
  flutter_bugly: 0.2.8

  # pull_to_refresh:
  #   git:
  #     url: https://github.com/YuzuWang/flutter_pulltorefresh.git
  #     ref: f07d8ed25b2776e28baddae105a64664cee2922c

  flip_card: ^0.4.4
  #腾讯云点播上传SDK
  flutter_txugcupload: ^0.0.2
  #腾讯直播
  tencent_live_fluttify: ^0.2.0+1
  #腾讯IM
  #TODO 已经将错误提交到上游代码，后期请使用新版本
  #more at https://github.com/JiangJuHong/FlutterTencentImPlugin/pull/101
  tencent_im_plugin:
    git:
      url: https://gitee.com/laiiihz/FlutterTencentImPlugin
  #瀑布流
  waterfall_flow: 2.0.3
  #相机
  camera: ^0.5.8+7
  #工具类库
  common_utils: ^1.2.1
  #视频剪辑
  video_trimmer: ^0.2.7

  #点赞组件
  many_like: ^0.0.6

  wakelock:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

    #TODO 重构图片assets
    - assets/home/
    - assets/user/

    - assets/activityImage/
    - assets/recook_launch_image/
    - assets/keys/server_rsa_public_key.pem
    - assets/keys/app_rsa_private_key.pem
    - assets/svg/
    - assets/icon/
    - assets/sound/recook_scan.mp3
    - assets/weatherCake/
    - assets/share_bottom/
    - assets/json/
    - assets/lottery/
    - assets/static/
    - assets/lottery_redeem/
    - assets/shop/
    - assets/header/
    - assets/live/
  fonts:
    - family: AppIcons
      fonts:
        - asset: static/font/iconfont.ttf
