name: recook
description: Recook Market App.
publish_to: "none"

version: 2.0.0-dev+329
environment:
  sdk: ">=2.10.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  timeline_tile: 0.1.2
  # 高德定位
  amap_flutter_location: ^3.0.0
  #高德基础依赖库
  amap_flutter_base: 3.0.0
  # 拼音
  lpinyin: 1.0.9
  # 城市列表
  azlistview: 0.1.2
  # 农历
  lunar_calendar_converter: 1.0.4+1
  # 进度条 视频录制
  percent_indicator: ^2.1.7+4

  #扫码提示音
  just_audio: ^0.7.3

  # 展示二维码
  qr_flutter: ^3.2.0

  flutter_qr_reader:
    git:
      url: https://github.com/customPub/flutter_qr_reader

  webview_flutter: ^2.0.0

#  video_player: ^2.0.0
#  chewie: ^1.0.0


  #解决部分机型画面乱码撕裂的问题
  flutter_tencentplayer:
    git:
      url: https://github.com/qq326646683/flutter_tencentplayer.git

  screen: 0.0.5

  url_launcher: ^5.1.3

  # 权限组件
  permission_handler: ^8.0.1

  cupertino_icons: ^1.0.2

  # 全局状态控制
  flutter_redux: ^0.7.0

  # json解析
  json_annotation: ^4.0.1

  # 路径
  path_provider: ^2.0.1
  path:

  # 网络请求
  dio: ^4.0.0-prev3

  # loading界面
  flutter_spinkit: ^3.1.0

  # toast提示
  oktoast: 2.3.2

  # 应用信息
  package_info: ^2.0.0

  #缓存图片
  #  cached_network_image: ^1.1.0
  extended_text: ^5.0.4
  extended_image: ^3.0.0
  # image_gallery_saver: ^1.2.1

  # 图片压缩
  flutter_image_compress: 0.6.3
  image_cropper: ^1.4.0

#  # svg
#  flutter_svg: ^0.21.0-nullsafety.0
#
#  sprintf: 4.0.2

  # 下拉刷新
  #
  #    现版本将smart_refresher.dart 中的enableOverScroll 去掉了，手动加上，具体代码在refresh_widget.dart中  #########################3
  #
  pull_to_refresh: ^1.6.4
  flutter_gifimage: ^1.0.0

  # 微信登录 支付等
  fluwx: ^3.6.1+4
    # git:
    #   url: http://test.akuhotel.com:8099/laiiihz/fluwx.git

  #
  # 源码 TobiasPlugin.m
  # 判断支付宝是否安装时  源码不正确  应将 alipays 改为 alipay #########################3
  #
  tobias: ^2.1.2+1

  # 小数据缓存
  shared_preferences: ^2.0.5

  # 屏幕适配
  flutter_screenutil: 5.0.0

  #轮播图
  flutter_swiper_null_safety: ^1.0.2

  # icons
  flutter_icons: 1.1.0

  # 腾讯云点播上传SDK
#  flutter_txugcupload: ^0.0.3
#
#  flutter_union_pay: ^0.0.4

#  meiqia_flutter:
#    git:
#      url: https://github.com/Mocaris/meiqia_flutter

  # 加密
  encrypt: ^5.0.0

  # 时间选择器 #该版本有报错 未修改
  flutter_datetime_picker: ^1.5.1
  #日期选择器
  flutter_custom_calendar:
    git:
      url:
        https://gitee.com/laiiihz/flutter_custom_calendar

  # 侧滑item
  flutter_slidable: 0.5.7

  # 图片选择
  photo:
    git:
      url: https://github.com/customPub/flutter_photo
      ref: patch-1
  # wechat_assets_picker: ^2.2.0+2

  image_gallery_saver: 1.7.1
  # 因为项目compileSdkVersion 28
  # 第三方包compileSdkVersion 是27 所以需要修改 不然build会出错
  #
  # flutter_bugly:
  #   git:
  #     url: https://github.com/crazecoder/flutter_bugly.git
  #     ref: dev
#  flutter_bugly: 0.2.8 安全检查原因暂时停用

  # pull_to_refresh:
  #   git:
  #     url: https://github.com/YuzuWang/flutter_pulltorefresh.git
  #     ref: f07d8ed25b2776e28baddae105a64664cee2922c

#  flip_card: ^0.4.4


  #腾讯直播
#  tencent_live_fluttify:
#    git:
#      url: https://github.com/customPub/tencent_live_fluttify
  #腾讯IM
  #TODO 已经将错误提交到上游代码，后期请使用新版本
  #more at https://github.com/JiangJuHong/FlutterTencentImPlugin/pull/101
#  tencent_im_plugin:
#    git:
#      url: https://github.com/customPub/tencent_im_plugin
  #瀑布流
  waterfall_flow: ^2.0.3
  #相机
  camera: ^0.5.8+7
  #工具类库
  flustars: ^2.0.1
  #视频剪辑
#  video_trimmer: ^0.5.4
#  video_trimmer:
#    git:
#      url: https://github.com/customPub/video_trimmer
#      #ref: 1761a6454623f19ef1d1c9b24f26dad47c2587b2


  #加载html
  flutter_widget_from_html_core: ^0.6.2

  #展开组件
  expandable: ^5.0.1

  #提示红点组件
  #badges: ^2.0.1

  #极光推送
  jpush_flutter: 2.2.3

  #缓存图片 解决金刚区图加载缓慢的问题
  cached_network_image: ^3.1.0

  hive: ^2.0.0
  hive_flutter: ^1.0.0

  pin_input_text_field: ^4.0.0
  velocity_x: ^3.3.0

  device_info: ^2.0.0
  #日志
  power_logger:
      git:
        url: https://git.oa00.com/flutter_pub/power_logger.git

  bot_toast: ^3.0.5
  get: ^3.26.0


  #跳转到应用市场进行更新
  launch_review: ^3.0.1

  widget_to_image: ^2.0.0


  flutter_picker: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.0.2
  grinder:
  import_sorter:
  yaml: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

    #TODO 重构图片assets
    - assets/home/
    - assets/user/
    - assets/ticket/
    - assets/recook_launch_image/
    - assets/svg/
    - assets/icon/
    - assets/sound/recook_scan.mp3
    - assets/weatherCake/
    - assets/share_bottom/
    - assets/json/
    - assets/static/
    - assets/shop/
    - assets/header/
    - assets/live/
    - assets/weather/
    - assets/wholesale/
  fonts:
    - family: AppIcons
      fonts:
        - asset: static/font/iconfont.ttf

    - family: HeadFont
      fonts:
        - asset: static/font/YouSheBiaoTiHei-2.ttf

import_sorter:
  emojis: true
  comments: false


