name: recook
description: Recook Market App.
publish_to: "none"

version: 1.10.0-nullsafety+300
environment:
  sdk: ">=2.10.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  timeline_tile: 0.1.2
  # 高德定位
  # amap_location_fluttify: ^0.18.0
  amap_flutter_location: ^1.0.1
  # icons
  flutter_icons: 1.1.0
  # 拼音
  lpinyin: 1.0.9
  # 城市列表
  azlistview: 0.1.2
  # 农历
  lunar_calendar_converter:
    1.0.4+1
    # 进度条
  percent_indicator: ^2.1.7+4
  # 头部滚动视图下拉刷新
  # extended_nested_scroll_view: ^0.3.6
  # 声音播放
  # soundpool: 1.0.1
  ## 暂时关闭声音播放
  #flutter_audio_player: 0.1.2
  just_audio: ^0.7.3
  # 第三方分享功能
  sharesdk_plugin:
    git:
      url: http://159.75.73.143:8080/third_packages/ShareSDK-For-Flutter
      path: sharesdk_plugin

  # 展示二维码
  qr_flutter: ^3.2.0
  # 二维码
  # barcode_scan: ^1.0.0
  flutter_qr_reader:
    git:
      url: https://gitee.com/laiiihz/flutter_qr_reader
      ref: 3e4824752f4fa50c30ecd415341a3a779db01922

  webview_flutter: ^1.0.7
  # 网页组件
  # webview_flutter:
  #   git:
  #     url: https://github.com/haysuperman/webview_flutter.git
  #     ref: 7045d9667dfe41c59f5f4a100d2335ec42f4e1de
  #
  url_launcher: ^5.1.3
  # 视频组件
  video_player: ^2.0.2
  chewie: ^1.0.0

  # 权限组件
  permission_handler: 3.3.0

  #邀请码相关第三方安装
  openinstall_flutter_plugin: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  sprintf: 4.0.2
  # 分享sdk
  # sharesdk: ^1.1.8
  # 全局状态控制
  flutter_redux: ^0.7.0

  # json解析
  json_annotation: ^4.0.1

  # 路径
  path_provider: ^2.0.1
  path:

  # 网络请求
  dio: ^4.0.0-prev3

  # loading界面
  flutter_spinkit: ^3.1.0

  # toast提示
  oktoast: 2.3.2

  # 应用信息
  package_info: ^2.0.0

  #缓存图片
  #  cached_network_image: ^1.1.0
  extended_text: ^5.0.4
  extended_image: ^3.0.0
  date_format: 1.0.8
  # image_gallery_saver: ^1.2.1

  # 图片压缩
  flutter_image_compress: 0.6.3
  image_cropper: ^1.4.0

  # svg
  flutter_svg: ^0.21.0-nullsafety.0

  # 下拉刷新
  #
  #    现版本将smart_refresher.dart 中的enableOverScroll 去掉了，手动加上，具体代码在refresh_widget.dart中  #########################3
  #
  pull_to_refresh: ^1.6.4
  flutter_gifimage: ^1.0.0

  # 微信登录 支付等
  fluwx: ^2.6.2
    # git:
    #   url: http://test.akuhotel.com:8099/laiiihz/fluwx.git

  #
  # 源码 TobiasPlugin.m
  # 判断支付宝是否安装时  源码不正确  应将 alipays 改为 alipay #########################3
  #
  tobias: 2.0.0-nullsafety.3

  # 小数据缓存
  shared_preferences: ^2.0.5

  # 屏幕适配
  flutter_screenutil: ^0.5.3

  # banner
  banner_view: ^1.1.2

  # meiqia_plugin: 0.0.2
  meiqia_plugin:
    git:
      url: https://github.com/haysuperman/meiqia
      ref: bfa6b9d81c079a4d1ce86ad611301966fa849538
      # ref: a16c54c40259d4c5bcf8f8da66379fe68a1115f1

  #  flutter_bugly: ^0.2.3+1

  # 加密
  encrypt: 3.2.0

  # 时间选择器
  flutter_datetime_picker: ^1.5.0

  # 侧滑item
  flutter_slidable: 0.5.7
  # flutter_slidable:
  #   git:
  #     url: https://github.com/haysuperman/flutter_slidable
  #     ref: 4073e1ff7db967aad4f97f0eee5909c5f8f339b5

  # 图片选择
  photo:
    git:
      url: http://159.75.73.143:8080/laiiihz/flutter_photo
      ref: patch-1
  # wechat_assets_picker: ^2.2.0+2

  image_gallery_saver: 1.5.0
  # 因为项目compileSdkVersion 28
  # 第三方包compileSdkVersion 是27 所以需要修改 不然build会出错
  #
  # flutter_bugly:
  #   git:
  #     url: https://github.com/crazecoder/flutter_bugly.git
  #     ref: dev
  flutter_bugly: 0.2.8

  # pull_to_refresh:
  #   git:
  #     url: https://github.com/YuzuWang/flutter_pulltorefresh.git
  #     ref: f07d8ed25b2776e28baddae105a64664cee2922c

  flip_card: ^0.4.4
  #腾讯云点播上传SDK
  flutter_txugcupload: ^0.0.3
  #腾讯直播
  tencent_live_fluttify:
    git:
      url: http://test.akuhotel.com:8099/laiiihz/tencent_live_fluttify.git
  #腾讯IM
  #TODO 已经将错误提交到上游代码，后期请使用新版本
  #more at https://github.com/JiangJuHong/FlutterTencentImPlugin/pull/101
  tencent_im_plugin:
    git:
      url: https://gitee.com/laiiihz/FlutterTencentImPlugin
  #瀑布流
  waterfall_flow: ^2.0.3
  #相机
  camera: ^0.5.8+7
  #工具类库
  flustars: ^2.0.1
  #视频剪辑
  video_trimmer:
    git:
      url: http://159.75.73.143:8080/laiiihz/video_trimmer

  #点赞组件
  many_like: ^0.0.6

  flutter_markdown:

  flutter_union_pay:
    git:
      url: https://github.com/laiiihz/flutter_union_pay

  package_signature: ^0.1.1

  raw_toast: ^0.0.1

  hive: ^2.0.0
  hive_flutter: ^1.0.0

  pin_input_text_field: ^4.0.0
  velocity_x: ^2.6.0

  animations:
  device_info: ^2.0.0
  clipboard_listener: ^1.0.0
  power_logger: ^1.0.1-nullsafety.1

  bot_toast: ^3.0.5
  get: ^3.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^4.0.2
  grinder:
  import_sorter:

flutter:
  uses-material-design: true
  assets:
    - assets/

    #TODO 重构图片assets
    - assets/home/
    - assets/user/

    - assets/activityImage/
    - assets/recook_launch_image/
    - assets/svg/
    - assets/icon/
    - assets/sound/recook_scan.mp3
    - assets/weatherCake/
    - assets/share_bottom/
    - assets/json/
    - assets/lottery/
    - assets/static/
    - assets/lottery_redeem/
    - assets/shop/
    - assets/header/
    - assets/live/
  fonts:
    - family: AppIcons
      fonts:
        - asset: static/font/iconfont.ttf
import_sorter:
  emojis: true
  comments: false

