name: recook
description: Recook Market App.
publish_to: "none"

version: 2.1.1-dev+417
environment:
  sdk: '>=2.12.0 <3.0.0'

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  timeline_tile: 2.0.0
  # 高德定位
  amap_flutter_location: ^3.0.0
  #高德基础依赖库
  amap_flutter_base: 3.0.0
  # 拼音
  lpinyin: 2.0.0
  # 城市列表
  azlistview: 2.0.0


#  # 农历
  lunar_calendar_converter_new: ^2.0.0

  # 进度条 视频录制
  percent_indicator: ^3.0.1

  #扫码提示音
  just_audio: ^0.7.3

  # 展示二维码
  qr_flutter: ^4.0.0

  #扫码
  scan: ^1.6.0

  #重复引用
#  image_picker: ^0.8.5
  #重复引用
  webview_flutter: 2.0.4

  video_player: ^2.0.0
  chewie: ^1.0.0


#  screen:
#    git:
#      url: https://github.com/xwz1999/flutter_screen.git

  #重复引用
#  url_launcher: any

  # 权限组件
  permission_handler: ^8.0.1

  cupertino_icons: ^1.0.2

  # 全局状态控制
  flutter_redux: ^0.8.0

  # json解析
  json_annotation: ^4.0.1

  # 路径  #重复引用
#  path_provider: ^2.0.1
  path:

  # 网络请求
  dio: ^4.0.0-prev3

  # loading界面
  flutter_spinkit: ^5.0.0

  # toast提示
  oktoast: 3.0.0

  # 应用信息
  package_info: ^2.0.0

  #缓存图片
  #  cached_network_image: ^1.1.0
  extended_text: any
#  extended_image: ^3.0.0
  # image_gallery_saver: ^1.2.1

  # 图片压缩
  flutter_image_compress: 1.1.0
  image_cropper: 1.4.0


  # 下拉刷新
  #
  #    现版本将smart_refresher.dart 中的enableOverScroll 去掉了，手动加上，具体代码在refresh_widget.dart中  #########################3
  #
  pull_to_refresh: ^2.0.0


  flutter_gifimage:
    git:
      url:
        https://gitee.com/zwx19990815/flutter_gifimage.git

#  flutter_gifimage: ^1.0.0

  # 微信登录 支付等
  fluwx: 3.6.1+4
    # git:
    #   url: http://test.akuhotel.com:8099/laiiihz/fluwx.git

  #
  # 源码 TobiasPlugin.m
  # 判断支付宝是否安装时  源码不正确  应将 alipays 改为 alipay #########################3
  #
  tobias: ^2.1.2+1

  # 小数据缓存  #重复引用
#  shared_preferences: ^2.0.5

  # 屏幕适配
  flutter_screenutil: 5.0.0

  #轮播图
  flutter_swiper_null_safety: ^1.0.2

  # icons
#  flutter_icons: 1.1.0

  # 腾讯云点播上传SDK
#  flutter_txugcupload: ^0.0.3
#
#  flutter_union_pay: ^0.0.4


  # 加密
  encrypt: ^5.0.0

  # 时间选择器 #该版本有报错 未修改
  flutter_datetime_picker: ^1.5.1
  #日期选择器
  flutter_custom_calendar:
    git:
      url:
        https://gitee.com/zwx19990815/flutter_custom_calendar
      ref:
        2e9b7f6
        #c1b3c0c

  # 侧滑item
#  flutter_slidable: 0.5.7


  wechat_assets_picker: ^7.0.0

  wechat_camera_picker: any

  image_gallery_saver: 1.7.1


  #腾讯直播
#  tencent_live_fluttify:
#    git:
#      url: https://github.com/customPub/tencent_live_fluttify
  #腾讯IM
  #TODO 已经将错误提交到上游代码，后期请使用新版本
  #more at https://github.com/JiangJuHong/FlutterTencentImPlugin/pull/101
#  tencent_im_plugin:
#    git:
#      url: https://github.com/customPub/tencent_im_plugin
  #瀑布流
  waterfall_flow: ^3.0.0
  #相机
#  camera: ^0.9.8+1
  #工具类库
  flustars: ^2.0.1

  #加载html
  flutter_widget_from_html_core: ^0.6.2

  #展开组件
  expandable: ^5.0.1

  #提示红点组件
  #badges: ^2.0.1

  #极光推送
  jpush_flutter: 2.2.3

  #缓存图片 解决金刚区图加载缓慢的问题
  cached_network_image: ^3.1.0

  hive: ^2.0.0
  hive_flutter: ^1.0.0

  pin_input_text_field: ^4.0.0
  velocity_x: 3.3.0

  device_info: ^2.0.0
  #日志
  power_logger:
      git:
        url: https://git.oa00.com/flutter_pub/power_logger.git

  bot_toast: ^4.0.2
  get: 4.0.2


  #跳转到应用市场进行更新
  launch_review: ^3.0.1

  widget_to_image: ^2.0.0

  uni_links: ^0.5.1

  flutter_picker: ^2.0.3

  #日历组件
  table_calendar: 3.0.0
  #萝卜丝客服
  bytedesk_kefu:
    git:
      url:
        https://github.com/xwz1999/bytedesk-flutter.git
      path:
        bytedesk_kefu
      ref:
        'b6596fc'
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: any
  grinder:
  import_sorter:
  yaml: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

    #TODO 重构图片assets
    - assets/home/
    - assets/user/
    - assets/ticket/
    - assets/recook_launch_image/
    - assets/svg/
    - assets/icon/
    - assets/sound/recook_scan.mp3
    - assets/weatherCake/
    - assets/share_bottom/
    - assets/json/
    - assets/static/
    - assets/shop/
    - assets/header/
    - assets/live/
    - assets/weather/
    - assets/wholesale/
    - assets/life/
    - assets/audio/
    - assets/images/chat/
    - assets/images/feedback/
  fonts:
    - family: AppIcons
      fonts:
        - asset: static/font/iconfont.ttf

    - family: HeadFont
      fonts:
        - asset: static/font/YouSheBiaoTiHei-2.ttf

import_sorter:
  emojis: true
  comments: false


